"""create_tickets_table

Revision ID: 3d0546d0b919
Revises: d6e482473d34
Create Date: 2025-06-27 06:05:37.028200+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d0546d0b919"
down_revision = "d6e482473d34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("creator_id", sa.BigInteger(), nullable=False),
        sa.Column("assigned_to", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.Column("is_shadow_closed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tickets_assigned_to", "tickets", ["assigned_to"], unique=False
    )
    op.create_index(
        "idx_tickets_channel_id", "tickets", ["channel_id"], unique=False
    )
    op.create_index(
        "idx_tickets_created_at", "tickets", ["created_at"], unique=False
    )
    op.create_index(
        "idx_tickets_creator_id", "tickets", ["creator_id"], unique=False
    )
    op.create_index(
        "idx_tickets_guild_status",
        "tickets",
        ["guild_id", "status"],
        unique=False,
    )
    op.create_index("idx_tickets_status", "tickets", ["status"], unique=False)
    op.create_index(
        op.f("ix_tickets_assigned_to"),
        "tickets",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tickets_channel_id"), "tickets", ["channel_id"], unique=True
    )
    op.create_index(
        op.f("ix_tickets_creator_id"), "tickets", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_tickets_guild_id"), "tickets", ["guild_id"], unique=False
    )
    op.create_index(op.f("ix_tickets_id"), "tickets", ["id"], unique=False)
    op.create_index(
        op.f("ix_tickets_status"), "tickets", ["status"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_users_created_at", "users", ["created_at"], unique=False
    )
    op.create_index(
        "idx_users_discord_id", "users", ["discord_id"], unique=False
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_index(
        op.f("ix_users_discord_id"), "users", ["discord_id"], unique=True
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("assigned_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_role_assignments_guild_role",
        "role_assignments",
        ["guild_id", "role"],
        unique=False,
    )
    op.create_index(
        "idx_role_assignments_user_guild",
        "role_assignments",
        ["user_id", "guild_id"],
        unique=True,
    )
    op.create_index(
        "idx_role_assignments_user_id",
        "role_assignments",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_assignments_guild_id"),
        "role_assignments",
        ["guild_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_assignments_id"),
        "role_assignments",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_role_assignments_id"), table_name="role_assignments"
    )
    op.drop_index(
        op.f("ix_role_assignments_guild_id"), table_name="role_assignments"
    )
    op.drop_index(
        "idx_role_assignments_user_id", table_name="role_assignments"
    )
    op.drop_index(
        "idx_role_assignments_user_guild", table_name="role_assignments"
    )
    op.drop_index(
        "idx_role_assignments_guild_role", table_name="role_assignments"
    )
    op.drop_table("role_assignments")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_discord_id"), table_name="users")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_users_discord_id", table_name="users")
    op.drop_index("idx_users_created_at", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_guild_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_creator_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_channel_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_assigned_to"), table_name="tickets")
    op.drop_index("idx_tickets_status", table_name="tickets")
    op.drop_index("idx_tickets_guild_status", table_name="tickets")
    op.drop_index("idx_tickets_creator_id", table_name="tickets")
    op.drop_index("idx_tickets_created_at", table_name="tickets")
    op.drop_index("idx_tickets_channel_id", table_name="tickets")
    op.drop_index("idx_tickets_assigned_to", table_name="tickets")
    op.drop_table("tickets")
    # ### end Alembic commands ###
