"""create_messages_table

Revision ID: 34cf95c621d1
Revises: a1678e8e892c
Create Date: 2025-07-08 01:53:05.131066+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34cf95c621d1"
down_revision = "a1678e8e892c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=True),
        sa.Column("is_staff_only", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("edited_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_author_id"), "messages", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_messages_is_staff_only"),
        "messages",
        ["is_staff_only"],
        unique=False,
    )
    op.create_index(
        "ix_messages_ticket_created",
        "messages",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_ticket_id"), "messages", ["ticket_id"], unique=False
    )
    op.create_index(
        "ix_messages_ticket_staff_only",
        "messages",
        ["ticket_id", "is_staff_only"],
        unique=False,
    )
    op.alter_column(
        "guilds",
        "id",
        existing_type=sa.BIGINT(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "guilds",
        "ticket_category_name",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "auto_archive_hours",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "auto_transcript",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "guilds",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index(op.f("ix_guilds_id"), "guilds", ["id"], unique=False)
    op.alter_column(
        "role_assignments",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "role_assignments",
        "user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "role_assignments",
        "assigned_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "tickets", "channel_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "tickets", "channel_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "role_assignments",
        "assigned_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "role_assignments",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "role_assignments",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_guilds_id"), table_name="guilds")
    op.alter_column(
        "guilds",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "guilds",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "guilds",
        "auto_transcript",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "auto_archive_hours",
        existing_type=sa.BIGINT(),
        server_default=sa.text("(24)"),
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "ticket_category_name",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("'🎫 Tickets'"),
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "id",
        existing_type=sa.BIGINT(),
        nullable=True,
        autoincrement=True,
    )
    op.drop_index("ix_messages_ticket_staff_only", table_name="messages")
    op.drop_index(op.f("ix_messages_ticket_id"), table_name="messages")
    op.drop_index("ix_messages_ticket_created", table_name="messages")
    op.drop_index(op.f("ix_messages_is_staff_only"), table_name="messages")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_author_id"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
