"""create_ticket_participants_table

Revision ID: a1678e8e892c
Revises: 1b2c3d4e5f6g
Create Date: 2025-07-02 01:52:18.921115+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1678e8e892c"
down_revision = "1b2c3d4e5f6g"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_participants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ticket_id", "user_id", name="uq_ticket_participant"
        ),
    )
    op.create_index(
        op.f("ix_ticket_participants_id"),
        "ticket_participants",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_participants_ticket_id"),
        "ticket_participants",
        ["ticket_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_participants_user_id"),
        "ticket_participants",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "guilds",
        "id",
        existing_type=sa.BIGINT(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "guilds",
        "ticket_category_name",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "auto_archive_hours",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "auto_transcript",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "guilds",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index(op.f("ix_guilds_id"), "guilds", ["id"], unique=False)
    op.alter_column(
        "role_assignments",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "role_assignments",
        "user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "role_assignments",
        "assigned_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "tickets", "channel_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "tickets", "channel_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "role_assignments",
        "assigned_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "role_assignments",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "role_assignments",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_guilds_id"), table_name="guilds")
    op.alter_column(
        "guilds",
        "updated_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "guilds",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "guilds",
        "auto_transcript",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "auto_archive_hours",
        existing_type=sa.BIGINT(),
        server_default=sa.text("(24)"),
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "ticket_category_name",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("'🎫 Tickets'"),
        existing_nullable=False,
    )
    op.alter_column(
        "guilds",
        "id",
        existing_type=sa.BIGINT(),
        nullable=True,
        autoincrement=True,
    )
    op.drop_index(
        op.f("ix_ticket_participants_user_id"),
        table_name="ticket_participants",
    )
    op.drop_index(
        op.f("ix_ticket_participants_ticket_id"),
        table_name="ticket_participants",
    )
    op.drop_index(
        op.f("ix_ticket_participants_id"), table_name="ticket_participants"
    )
    op.drop_table("ticket_participants")
    # ### end Alembic commands ###
